name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  sonar:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build project
        run: mvn clean install

      - name: SonarCloud Analysis
        run: |
          mvn sonar:sonar `
            -D"sonar.organization=maxgrinderafk" `
            -D"sonar.projectKey=lab1" `
            -D"sonar.host.url=https://sonarcloud.io" `
            -D"sonar.login=${{ secrets.SONAR_TOKEN }}" `
            -D"sonar.branch.name=master"
        shell: cmd
